# Generated by Django 4.2.4 on 2023-08-11 20:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('daily_request', models.IntegerField(blank=True, null=True, verbose_name='Daily Request Limit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('F', 'Free Trial'), ('M', 'Monthly Subscription'), ('Y', 'Yearly Subscription')], default='F', max_length=1, verbose_name='Period Type')),
                ('period_duration', models.PositiveSmallIntegerField(default=30, help_text='The default value is 30 because a month has 30 days. expiry_date = start_date + period_duration', verbose_name='Period Duration')),
                ('start_date', models.DateField(default=datetime.date(2023, 8, 11), verbose_name='Start Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Paid Amount')),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_subscriptions', to='subscription.plan', verbose_name='Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255, verbose_name='Feature Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscription.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
            },
        ),
    ]
